server {
    listen 80;

    # Si la URL empieza con /api, mandalo al contenedor 'server'
    location /api/ {
        proxy_pass http://server:3001; 
        proxy_set_header Host $host;
    }

    # Todo lo demás son archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}